config/routes.rb
Stock::Application.routes.draw do
  namespace :requests do  namespace :transferences do  namespace :finished do  namespace :components do resources :details end end end end

  namespace :requests do  namespace :transferences do  namespace :finished do resources :components end end end

  get "entry/index", :to => "entry#index"

  get "activity", :to => 'activity#index'
  get 'activity/:id', :to => 'activity#show'

  get "stock/products/index", :to => "stock/products#index"
  get "stock/products/transactions", :to => "stock/products#transactions"
  get "stock/products/list_products"
  get "stock/products/list_components"
  
  get "stock/production/list_components"
  get "stock/production/list_products"
  get "stock/production/index", :to => "stock/production#index"
  get "stock/production/transactions", :to => "stock/production#transactions"

  get '/users', :to => 'users#index'

  namespace :stock do
    get "raw_material", :to => "raw_material#index"
    get "raw_material/list"
    get "raw_material/transactions", :to => "raw_material#transactions"
  end

  namespace :requests do  namespace :devolutions do  namespace :components do resources :details end end end

  namespace :orders do  namespace :productions do resources :details end end

  namespace :requests do  namespace :devolutions do  namespace :products do resources :details end end end

  namespace :requests do  namespace :transferences do  namespace :products do resources :details end end end

  namespace :requests do  namespace :transferences do  namespace :components do resources :details end end end

  namespace :requests do  namespace :purchases do  namespace :components do resources :details end end end

  namespace :products do  namespace :compositions do resources :details end end

  namespace :requests do  namespace :devolutions do resources :components end end

  namespace :orders do resources :productions end

  namespace :requests do  namespace :devolutions do resources :products end end

  namespace :requests do  namespace :transferences do resources :products end end

  namespace :requests do  namespace :transferences do resources :components end end

  namespace :requests do  namespace :purchases do resources :components end end

  namespace :products do resources :compositions end

  namespace :transactions do resources :statuses end

  namespace :locations do resources :cities end

  namespace :locations do resources :regions end

  namespace :locations do resources :countries end

  namespace :locations do resources :continents end

  namespace :components do resources :brands end

  namespace :components do  namespace :categories do resources :kinds end end

  namespace :settings do
    get '/', :to => 'settings#index'
    get 'permissions', :to => 'permissions#index'
    match 'permissions/:role_id', :to => 'permissions#of_role', :via => 'get'
    post 'permissions/save'
    resources :roles

    put 'configurations', :to => 'configurations#update'
    get 'company', :to => 'configurations#company'
  end

  namespace :components do
    resources :items
    resources :categories
  end

  devise_for :users, :path_names => {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }, :controllers => {
    registrations: 'users/registrations'
  }

  root :to => "stock/raw_material#index"

end

app/models/components.rb
module Components
  def self.table_name_prefix
    'components_'
  end
end

app/models/components/brand.rb
class Components::Brand < ActiveRecord::Base
  acts_as_paranoid
  has_paper_trail
  attr_accessible :description, :name
#  validates :name, :presence => true, :uniqueness => true, :length => { :maximum => 36 }
  has_many :components_items,:foreign_key => :marca_id, :class_name => Components::Item.to_s
  
  set_table_name "marcas"
  alias_attribute :description, :descripcion
  alias_attribute :name, :nombre
  validates :nombre, :presence => true, :uniqueness => true, :length => { :maximum => 36 }
end

app/models/components/categories.rb
module Components::Categories
  def self.table_name_prefix
    'components_categories_'
  end
end

app/models/components/categories/kind.rb
class Components::Categories::Kind < ActiveRecord::Base
   has_paper_trail
  attr_accessible :name
  validates :name, :presence => true #, :length => { :minimum => 2 }  
end

app/models/components/category.rb
class Components::Category < ActiveRecord::Base
  attr_accessible :description, :name, :finished
  has_many :components_items, :foreign_key => :categoria_id, :class_name => Components::Item.to_s
  validates :nombre, :presence => true, :uniqueness => true, :length => { :minimum => 2, :maximum => 40 }
  validates :descripcion, :length => { :maximum => 200 }
  has_paper_trail
  acts_as_paranoid
  
  set_table_name "categorias"
  
  alias_attribute :name, :nombre
  alias_attribute :description, :descripcion
  alias_attribute :finished, :vendible
  
  class << self
    def get_finished
      self.where("vendible = true")
    end
  end
end

app/models/components/item.rb
class Components::Item < ActiveRecord::Base
  acts_as_paranoid
    attr_accessible :brand, :brand_id, :category, :category_id, :code, :price, :description, :name, :minimum_quantity
  belongs_to :category, :foreign_key => :categoria_id,:class_name => Components::Category.to_s
  belongs_to :brand, :foreign_key => :marca_id,:class_name => Components::Brand.to_s
  validates_presence_of  :code, :name, :category_id, :brand_id, :minimum_quantity, :price
  has_many :raw_material_stocks, :foreign_key => :componente_id, :class_name => ::Stocks::Component.to_s
  has_many :production_stocks, :foreign_key => :componente_id, :class_name => ::Stocks::Production.to_s
  has_many :products_stocks, :foreign_key => :componente_id, :class_name => ::Stocks::Product.to_s
  has_paper_trail
  
  has_many :requests_transferences_components_details, :foreign_key => :componente_id, :class_name => Requests::Transferences::Components::Detail.to_s
  
  has_many :requests_devolutions_components_details, :foreign_key => :componente_id, :class_name => Requests::Devolutions::Components::Detail.to_s
  
  has_many :products_compositions_details, :foreign_key => :componente_id, :class_name => Products::Compositions::Detail.to_s
  
  has_many :requests_purchases_components_details, :foreign_key => :componente_id, :class_name => Requests::Purchases::Components::Detail.to_s  
    
    
  set_table_name "componentes"
  alias_attribute :name, :nombre
  alias_attribute :code, :codigo
  alias_attribute :minimum_quantity, :stock_minimo
  alias_attribute :description, :descripcion
  alias_attribute :category_id, :categoria_id
  alias_attribute :brand_id, :marca_id
  alias_attribute :price, :precio
  
  validates :codigo, :uniqueness => true
  
  class << self
    def get_finished
      components = []; 
      Components::Category.get_finished.each do |category|
        components.concat category.components_items
      end
      return components
    end
  end
  
  def raw_material_total_stock
    qty = raw_material_stocks.reduce do |s0, s1|
      s0.quantity += s1.quantity
      s0
    end

    qty.nil? ? 0 : qty.quantity
  end

  def production_total_stock
    qty = production_stocks.reduce do |s0, s1|
      s0.quantity += s1.quantity
      s0
    end

    qty.nil? ? 0 : qty.quantity
  end
end

app/models/requests/devolutions/component.rb
class Requests::Devolutions::Component < ActiveRecord::Base
   has_paper_trail
  acts_as_paranoid

   attr_accessible :number, :reason, :status_id, :user_id, :user, :header_id, :component_id, :component, :status

  has_many :details, :foreign_key => :devoluciones_componentes_id, :class_name => "Requests::Devolutions::Components::Detail"

  belongs_to :status,  :foreign_key => :estado_id, :class_name => "Transactions::Status"
  belongs_to :user, :foreign_key => :usuario_id 

#  validates :status_id, :presence => true #, :length => { :minimum => 2 }  
#  validates :user_id, :presence => true #, :length => { :minimum => 2 }  
#  validates :reason, :presence => true #, :length => { :minimum => 2 }  
  
  #auto_increment :column => :number
  auto_increment :column => :numero
  
  set_table_name "devoluciones_componentes"
  alias_attribute :number, :numero
  alias_attribute :reason, :motivo
  alias_attribute :user_id, :usuario_id
  alias_attribute :status_id, :estado_id

  validates :estado_id, :presence => true #, :length => { :minimum => 2 }  
  validates :usuario_id, :presence => true #, :length => { :minimum => 2 }  
  validates :motivo, :presence => true #, :length => { :minimum => 2 }  
    
  
  def close
    details.each do |d|
      qtty = d.quantity
      quantity_on_production = 0;
      d.component.production_stocks.map{|e| 
        quantity_on_production += e.component_quantity
      }
      if qtty > quantity_on_production
        return false
      end
    end
    sum = 0
    details.each do |d|
      id = d.component.id
      price = d.component.price
      qtty = d.quantity
      return false unless Stocks::Production.subtract({component_id: id, component_quantity: qtty, component_price: price})
      Stocks::Component.create!({component_id: id, quantity: qtty, price: price})
#      Transaction.create!({
#        kind: self.class.to_s,
#        detail_kind: d.class.to_s,
#        detail_id: d.id,
#        from_stock: Stocks::Production.to_s,
#        to_stock: Stocks::Component.to_s,
#        is_component: true
#      })
      sum += price * qtty
    end
     
    
    entry_id = Accounting::Entry.create!({
      description: "Devoluciones de componentes y operaciones similares"    
    }).id
    
    debe_account_id = AppConfig.find('accounting_purchases_devolutions_id').value;

    haber_account_id = AppConfig.find('to_accounting_raw_materials_id').value 
    
    Accounting::Entries::Detail.create!({
      header_id: entry_id,
      value: sum,
      account_id: debe_account_id
    })
    Accounting::Entries::Detail.create!({
      header_id: entry_id,
      value: sum,
      account_id: haber_account_id
    })
   
    return true
  end
 
end

app/models/requests/devolutions/components.rb
module Requests::Devolutions::Components
  def self.table_name_prefix
    'requests_devolutions_components_'
  end
end

app/models/requests/devolutions/components/detail.rb
class Requests::Devolutions::Components::Detail < ActiveRecord::Base
  has_paper_trail
  acts_as_paranoid

  attr_accessible :component_id, :header_id, :quantity, :component, :requests_devolutions_component
#  validates :header_id, :presence => true #, :length => { :minimum => 2 }  
#  validates :component_id, :presence => true #, :length => { :minimum => 2 }  
#  validates :quantity, :presence => true, :numericality => { :greater_than => 0, :less_than => 2000000001 }#, :length => { :minimum => 2 }   
  belongs_to :requests_devolutions_component, :foreign_key => :devoluciones_componentes_id, :class_name => "Requests::Devolutions::Component"
  belongs_to :component, :foreign_key => :componente_id,  :class_name => Components::Item.to_s
  
  set_table_name "devoluciones_componentes_detalles"
  alias_attribute :quantity, :cantidad
  alias_attribute :header_id, :devoluciones_componentes_id
  alias_attribute :component_id, :componente_id

  validates :devoluciones_componentes_id, :presence => true #, :length => { :minimum => 2 }  
  validates :componente_id, :presence => true #, :length => { :minimum => 2 }  
  validates :cantidad, :presence => true, :numericality => { :greater_than => 0, :less_than => 2000000001 }
  
  after_create :increment_quantity
  def increment_quantity
    requests_devolutions_component.details.each  do |d|
      if d.component_id == component_id && d.id != id
        d.quantity += quantity
        d.save
        self.destroy
      end
    end
  end

  
end

app/models/requests/purchases/component.rb
class Requests::Purchases::Component < ActiveRecord::Base
  acts_as_paranoid
   has_paper_trail
  attr_accessible :status_id, :status, :user_id, :user, :header, :header_id, :number

  has_many :details, :foreign_key => :pedidos_compras_componentes_id, :class_name => Requests::Purchases::Components::Detail.to_s

  belongs_to :status,  :foreign_key => :estado_id, :class_name => Transactions::Status.to_s
  belongs_to :user, :foreign_key => :usuario_id

#  validates :status_id, :presence => true
#  validates :user_id, :presence => true
  
#  auto_increment :column => :number  
  auto_increment :column => :numero
   
  set_table_name "pedidos_compras_componentes"
  alias_attribute :number, :numero
  alias_attribute :status_id, :estado_id
  alias_attribute :user_id, :usuario_id

  validates :estado_id, :presence => true
  validates :usuario_id, :presence => true
  
  class << self
    def generated_by_system
      system_user_id = AppConfig.find('system_user_id').value
      open_status_id = AppConfig.find('open_status_id').value
      return self.where('usuario_id = ? AND estado_id = ?', system_user_id, open_status_id)
    end
  end
  
  def close
  
    sum = 0
    
    details.each do |d|
      
      sum += d.component.price * d.quantity
      
      Stocks::Component.create!({
        component_id: d.component.id,
        quantity: d.quantity,
        price: d.component.price
      })
      
#      Transaction.create!({
#        kind: self.class.to_s,
#        detail_kind: d.class.to_s,
#        detail_id: d.id,
#        from_stock: "Compras",
#        to_stock: Stocks::Component.to_s,
#        is_component: true
#      })
    
    end
    
    entry_id = Accounting::Entry.create!({
      description: "Compra de componentes"    
    }).id
    
    debe_account_id = AppConfig.find('accounting_raw_materials_id').value
    
    haber_account_id = AppConfig.find('to_accounting_box_id').value
    
    Accounting::Entries::Detail.create!({
      header_id: entry_id,
      value: sum,
      account_id: debe_account_id,
    })
    Accounting::Entries::Detail.create!({
      header_id: entry_id,
      value: sum,
      account_id: haber_account_id,
    })
    
    return true
  end
  
end

app/models/requests/purchases/components.rb
module Requests::Purchases::Components
  def self.table_name_prefix
    'requests_purchases_components_'
  end
end

app/models/requests/purchases/components/detail.rb
class Requests::Purchases::Components::Detail < ActiveRecord::Base
  acts_as_paranoid
   has_paper_trail
  attr_accessible :component_id, :header_id, :quantity, :component, :requests_purchases_component
#  validates :component_id, :presence => true
#  validates :header_id, :presence => true
#  validates :quantity, :presence => true, :numericality => { :greater_than => 0, :less_than => 2000000001 }
  
  belongs_to :component,  :foreign_key => :componente_id, :class_name => Components::Item.to_s
  belongs_to :requests_purchases_component, :foreign_key => :pedidos_compras_componentes_id, :class_name => Requests::Purchases::Component.to_s
  
  set_table_name "pedidos_compras_componentes_detalles"
  alias_attribute :quantity, :cantidad
  alias_attribute :header_id, :pedidos_compras_componentes_id
  alias_attribute :component_id, :componente_id
  
  validates :componente_id, :presence => true
  validates :pedidos_compras_componentes_id, :presence => true
  validates :cantidad, :presence => true, :numericality => { :greater_than => 0, :less_than => 2000000001 }

  after_create :increment_quantity
  def increment_quantity
    requests_purchases_component.details.each  do |d|
      if d.component_id == component_id && d.id != id
        d.quantity += quantity
        d.save
        self.destroy
      end
    end
  end
  
end

app/models/requests/transferences.rb
module Requests::Transferences
  def self.table_name_prefix
    'requests_transferences_'
  end
end

app/models/requests/transferences/components.rb
module Requests::Transferences::Components
  def self.table_name_prefix
    'requests_transferences_components_'
  end
end

app/models/requests/transferences/components/detail.rb
class Requests::Transferences::Components::Detail < ActiveRecord::Base
   has_paper_trail
  acts_as_paranoid

  attr_accessible :component_id, :header_id, :quantity, :component, :requests_transferences_component
#  validates :component_id, :presence => true #, :length => { :minimum => 2 }  
#  validates :header_id, :presence => true #, :length => { :minimum => 2 }  
#  validates :quantity, :presence => true, :numericality => { :greater_than => 0, :less_than => 2000000001 }
  
  belongs_to :component, :foreign_key => :componente_id,  :class_name => Components::Item.to_s
  belongs_to :requests_transferences_component, :foreign_key => :solicitud_transferencia_componentes_id, :class_name => "Requests::Transferences::Component"
  
  set_table_name "solicitudes_transferencias_componentes_detalles"
  alias_attribute :quantity, :cantidad
  alias_attribute :header_id, :solicitud_transferencia_componentes_id
  alias_attribute :component_id, :componente_id

  validates :componente_id, :presence => true #, :length => { :minimum => 2 }  
  validates :solicitud_transferencia_componentes_id, :presence => true #, :length => { :minimum => 2 }  
  validates :cantidad, :presence => true, :numericality => { :greater_than => 0, :less_than => 2000000001 } 
  
  class << self
    def get_by_header_and_component component_id, header_id
     return self.where("componente_id = ? AND solicitud_transferencia_componentes_id = ?", component_id, header_id)
    end
  end 
  
  after_create :increment_quantity
  def increment_quantity
    requests_transferences_component.details.each  do |d|
      if d.component_id == component_id && d.id != id
        d.quantity += quantity
        d.save
        self.destroy
      end
    end
  end
  
end

app/models/requests/transferences/finished.rb
module Requests::Transferences::Finished
  def self.table_name_prefix
    'requests_transferences_finished_'
  end
end

app/views/requests/transferences/components/_form.html.haml
= form_for @requests_transferences_component, :html => { "data-remote"=>"true", style: "width:400px;" } do |f|
  - if @requests_transferences_component.errors.any?
    #error_explanation 
      %h2= "No se pudo guardar:"
      %ul
        - @requests_transferences_component.errors.full_messages.each do |msg|
          %li= msg
  
  .field
    = f.label :status_id, 'Estado'
    = f.collection_select(:status_id, Transactions::Status.all, :id, :name, { :disabled => lambda{|status| (@requests_transferences_component.status != @default_status && status == @reject_status) }, class: "required" })
      
  %div.ui-grid-a
    %div.ui-block-a
      %a.cancel{ data: {role:'button', icon: 'delete', theme: 'a' } } Cancelar
    %div.ui-block-b  
      %input{ close: "#componentPopup", type: 'submit', value: 'Guardar', data: { icon: 'plus', theme: 'b' } }

app/views/requests/transferences/components/edit.html.haml
%h3{ data: {role:"header", theme:"d"} } Editar pedido de componentes
%div{ data: {role: "content", theme: "c" } }

  = render 'form'

app/views/requests/transferences/components/edit.js.haml
:plain
  openPopup('#{escape_javascript render :file => "requests/transferences/components/edit", :formats => [:html]}');
  showNotice('#{ @notice }');  

app/views/requests/transferences/components/index.html.haml
= will_paginate @requests_transferences_components
%ul{ data: { role: 'listview', inset: 'true', theme: 'c', filter: 'true' } }
  %li{ data: { role: 'list-divider' } }
  
    %div{ class: "ui-grid-d" }
  
      %div{ class: "ui-block-a" } N&uacute;mero
          
      %div{ class: "ui-block-b" }  Estado
      
      %div{ class: "ui-block-c" }  Usuario
      
      %div{ class: "ui-block-d" }  Fecha
      
      %div{ class: "ui-block-e" }  Opciones
  
  - @requests_transferences_components.each do |requests_transferences_component|
    %li{ class: 'element detail'}
      %div{ class: "ui-grid-d" }
      
        %div{ class: "ui-block-a trim" }= requests_transferences_component.number
    
        %div{ class: "ui-block-b trim" }= requests_transferences_component.status.name
      
        %div{ class: "ui-block-c trim" }= requests_transferences_component.user.email
      
        %div{ class: "ui-block-d trim" }= requests_transferences_component.updated_at
  
        %div{ style:"width:262px;", class: "ui-block-e", data: { role: 'controlgroup', type: 'horizontal' } }
          - obj = requests_transferences_component
          - can_modify?(obj)
          - delete_css_class = !can?(:delete, obj) ? 'ui-disabled' : ''
          - edit_css_class = !can?(:edit, obj) ? 'ui-disabled' : ''
          %a{ href: requests_transferences_component_path(requests_transferences_component), data: { method: :delete, confirm: 'Esta seguro?', role: 'button', icon: 'delete', mini: 'true', remote: 'true' }, class: delete_css_class } Eliminar
          %a{ href: edit_requests_transferences_component_path(requests_transferences_component), data: { role: 'button', icon: 'grid', mini: 'true', remote: 'true'}, class: edit_css_class } Editar
          %a{ href: requests_transferences_component_path(requests_transferences_component), data: { role: 'button', icon: 'grid', mini: 'true', remote: 'true'} } Detalle
          
  - create_css_class = !can?(:create, Requests::Transferences::Component.new) ? 'ui-disabled' : ''
  = link_to 'Agregar  ', new_requests_transferences_component_path, { style: 'width: 250px; float: right', data: { role: 'button', theme: 'b', icon: 'new', remote: 'true' }, class: create_css_class }
  
%br    
%div{ data: { role: 'controlgroup', type: 'horizontal' } }
  %a{ href: "#", data: { role: 'button', mini: 'true', pdf: 'true', href: requests_transferences_components_url(:format => :pdf) } } Reporte

app/views/requests/transferences/components/index.js.haml
:plain
  changeContent('#page #content',
    '#{escape_javascript render :file => "requests/transferences/components/index", :formats => [:html]}'
  );
  showNotice('#{ @notice }');  

app/views/requests/transferences/components/new.html.haml
%h3{ data: {role:"header", theme:"d"} }  Agregar pedido

%div{ data: {role: "content", theme: "a" } }

  = render 'form'

-#= link_to 'Atras', requests_transferences_components_path

app/views/requests/transferences/components/new.js.haml
:plain
  openPopup('#{escape_javascript render :file => "requests/transferences/components/new", :formats => [:html]}');
  showNotice('#{ @notice }');  

app/views/requests/transferences/components/show.html.haml
%ul{ data: { role: 'listview', theme: 'c' } }
  %li{ data: { role: 'list-divider'} }
    %div{ class: "ui-grid-c" }
        
      %div{ class: "ui-block-a" } Número      
        
      %div{ class: "ui-block-b" } Estado
        
      %div{ class: "ui-block-c" } Usuario

      %div{ class: "ui-block-d" } Fecha
  %li
    %div{ class: "ui-grid-c" }
    
      %div{ class: "ui-block-a" }= @requests_transferences_component.number
    
      %div{ class: "ui-block-b" }= @requests_transferences_component.status.name
    
      %div{ class: "ui-block-c" }= @requests_transferences_component.user.email
      
      %div{ class: "ui-block-d" }= @requests_transferences_component.updated_at
    
  - @requests_transferences_components_details = @requests_transferences_component.details.paginate(:page => params[:page])
  - @requests_transferences_components_detail = Requests::Transferences::Components::Detail.new

%br
- obj = @requests_transferences_component
- if can_modify?(obj)
  %div#form
    = render 'requests/transferences/components/details/form'
%div#list
  = render 'requests/transferences/components/details/list'
  
= link_to 'Volver', requests_transferences_components_path, { style: 'width: 250px; float: left', data: { role: 'button', theme: 'c', remote: 'true' } }

- create_css_class = can?(:create, Requests::Transferences::Components::Detail) ? '' : 'ui-disabled'
= link_to 'Agregar  ', new_requests_transferences_components_detail_path(:header_id => @requests_transferences_component.id), { style: 'width: 250px; float: right', data: { role: 'button', theme: 'b', icon: 'new', remote: 'true' }, class: create_css_class }

-#    %div{ class: "ui-block-d" } :
-#    %div{ class: "ui-block-e" }= @requests_transferences_component.transaction_id  

app/views/requests/transferences/components/show.js.haml
:plain
  changeContent('#page #content',
    '#{escape_javascript render :file => "requests/transferences/components/show", :formats => [:html]}'
  );
  showNotice('#{ @notice }');  