config/routes.rb
Stock::Application.routes.draw do
  namespace :requests do  namespace :transferences do  namespace :finished do  namespace :components do resources :details end end end end

  namespace :requests do  namespace :transferences do  namespace :finished do resources :components end end end

  get "entry/index", :to => "entry#index"

  get "activity", :to => 'activity#index'
  get 'activity/:id', :to => 'activity#show'

  get "stock/products/index", :to => "stock/products#index"
  get "stock/products/transactions", :to => "stock/products#transactions"
  get "stock/products/list_products"
  get "stock/products/list_components"
  
  get "stock/production/list_components"
  get "stock/production/list_products"
  get "stock/production/index", :to => "stock/production#index"
  get "stock/production/transactions", :to => "stock/production#transactions"

  get '/users', :to => 'users#index'

  namespace :stock do
    get "raw_material", :to => "raw_material#index"
    get "raw_material/list"
    get "raw_material/transactions", :to => "raw_material#transactions"
  end

  namespace :requests do  namespace :devolutions do  namespace :components do resources :details end end end

  namespace :orders do  namespace :productions do resources :details end end

  namespace :requests do  namespace :devolutions do  namespace :products do resources :details end end end

  namespace :requests do  namespace :transferences do  namespace :products do resources :details end end end

  namespace :requests do  namespace :transferences do  namespace :components do resources :details end end end

  namespace :requests do  namespace :purchases do  namespace :components do resources :details end end end

  namespace :products do  namespace :compositions do resources :details end end

  namespace :requests do  namespace :devolutions do resources :components end end

  namespace :orders do resources :productions end

  namespace :requests do  namespace :devolutions do resources :products end end

  namespace :requests do  namespace :transferences do resources :products end end

  namespace :requests do  namespace :transferences do resources :components end end

  namespace :requests do  namespace :purchases do resources :components end end

  namespace :products do resources :compositions end

  namespace :transactions do resources :statuses end

  namespace :locations do resources :cities end

  namespace :locations do resources :regions end

  namespace :locations do resources :countries end

  namespace :locations do resources :continents end

  namespace :components do resources :brands end

  namespace :components do  namespace :categories do resources :kinds end end

  namespace :settings do
    get '/', :to => 'settings#index'
    get 'permissions', :to => 'permissions#index'
    match 'permissions/:role_id', :to => 'permissions#of_role', :via => 'get'
    post 'permissions/save'
    resources :roles

    put 'configurations', :to => 'configurations#update'
    get 'company', :to => 'configurations#company'
  end

  namespace :components do
    resources :items
    resources :categories
  end

  devise_for :users, :path_names => {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }, :controllers => {
    registrations: 'users/registrations'
  }

  root :to => "stock/raw_material#index"

end

app/models/orders.rb
module Orders
  def self.table_name_prefix
    'orders_'
  end
end

app/models/orders/production.rb
class Orders::Production < ActiveRecord::Base
   has_paper_trail
  acts_as_paranoid

  attr_accessible :status_id, :user_id, :number

  has_many :details, :foreign_key => :orden_produccion_id, :class_name => "Orders::Productions::Detail"

  belongs_to :status, :foreign_key => :estado_id, :class_name => "Transactions::Status"
  belongs_to :user,:foreign_key => :usuario_id

#  validates :status_id, :presence => true #, :length => { :minimum => 2 }  
#  validates :user_id, :presence => true #, :length => { :minimum => 2 }  
#  
  #auto_increment :column => :number
  auto_increment :column => :numero

  has_many :transferences, :foreign_key => :orden_produccion_id, :class_name => Requests::Transferences::Product.to_s
  
  before_destroy :destroy_requests_open
  
  set_table_name "ordenes_producciones"
  alias_attribute :number, :numero
  alias_attribute :status_id, :estado_id
  alias_attribute :user_id, :usuario_id


  validates :estado_id, :presence => true #, :length => { :minimum => 2 }  
  validates :usuario_id, :presence => true #, :length => { :minimum => 2 }  
    
  class << self
    def generated_by_system
      system_user_id = AppConfig.find('system_user_id').value
      open_status_id = AppConfig.find('open_status_id').value
      self.where('usuario_id = ? AND estado_id = ?', system_user_id, open_status_id)
    end
  end
  
    
  def destroy_requests_open
     open_status_id = AppConfig.find('open_status_id').value
     details.each do |dd|
      Requests::Transferences::Component.get_by_order_detail( dd.id, open_status_id).destroy_all
     end
  end
  
  def update_request
    system_user_id = AppConfig.find('system_user_id').value
    open_status_id = AppConfig.find('open_status_id').value

    details.each do |dd|
      request = Requests::Transferences::Component.get_by_order_detail( dd.id, open_status_id).first #|| request = Requests::Transferences::Component.create!({
#          user_id: system_user_id,
#          status_id: open_status_id,
#          order_detail_id: dd.id,
#        })
      
      return false unless request
      
      components = {}    
      dd.product.details.each do |c|
        qtty = c.quantity * dd.quantity
        if components[c.component.id.to_sym]
          components[c.component.id.to_sym] = components[c.component.id.to_sym] + qtty
        else
          components[c.component.id.to_sym] = qtty
        end
      end 
      components.each { |k, v| 
          detail = Requests::Transferences::Components::Detail.get_by_header_and_component(k, request.id).first
          if detail
            detail.quantity = v
            detail.save
          end
      }

    end   
    return true
  end  
  
  def generate_request

    system_user_id = AppConfig.find('system_user_id').value
    open_status_id = AppConfig.find('open_status_id').value
    
    requests_g = []
    
    details.each do |dd|
      components = {}    
      request = Requests::Transferences::Component.get_by_order_detail( dd.id, open_status_id).first
      if ! request
        request =  Requests::Transferences::Component.create!({
          user_id: system_user_id,
          status_id: open_status_id,
          order_detail_id: dd.id })
      
        dd.product.details.each do |c|
          qtty = c.quantity * dd.quantity
          if ! components[c.component.id.to_sym]
            components[c.component.id.to_sym] = qtty
          end
        end 
        components.each { |k, v| 
          detail = Requests::Transferences::Components::Detail.get_by_header_and_component(k, request.id).first
          if detail
            detail.quantity = v
            detail.save
          else 
            Requests::Transferences::Components::Detail.create!({
              component_id: k,
              quantity: v,     
              header_id: request.id  }) 
          end
        }
      else
        update_request
      end
      requests_g << request
    end
    
    requests_g.each do |r|
      r.destroy if r.details.empty?
    end
   
    return true
  end
  
  
  # When an order is closed
  def close
  
    products_transferences = Requests::Transferences::Product.create!({
      user_id: user.id,
      status_id: status.id,
      order_production_id: id
    });
    details.each do |d|
      Requests::Transferences::Products::Detail.create!({
        header_id: products_transferences.id,
        product_id: d.product.id,
        quantity: d.quantity,
        order_production_detail_id: d.id
      })
    end

    if ! products_transferences.close
      products_transferences.details.destroy_all
      products_transferences.destroy
      return false
    end
    
    sum = 0
    component_sum = 0
    details.each do |d|
#      Transaction.create!({
#        kind: self.class.to_s,
#        detail_kind: d.class.to_s,
#        detail_id: d.id,
#        from_stock: Stocks::Production.to_s,
#        to_stock: Stocks::Product.to_s,
#        is_component: false
#      })
      sum += d.product.price * d.quantity
      
      d.product.details.each do |dc|
        component_sum += dc.component.price * dc.quantity
      end
    end
    
    entry_id = Accounting::Entry.create!({
      description: "Transferencia de productos"    
    }).id
    
    debe_account_id = AppConfig.find('accounting_finished_product_id').value
    haber_account_id = AppConfig.find('to_accounting_products_in_process_id').value
    
    Accounting::Entries::Detail.create!({
      header_id: entry_id,
      value: sum,
      account_id: debe_account_id,
    })
    Accounting::Entries::Detail.create!({
      header_id: entry_id,
      value: component_sum,
      account_id: haber_account_id,
    })
    haber_account_id2 = AppConfig.find('to_accounting_production_recharge_id').value

    Accounting::Entries::Detail.create!({
      header_id: entry_id,
      value: sum - component_sum,
      account_id: haber_account_id2,
    })
    
    return true
  end
 
end

app/controllers/orders/productions/details_controller.rb
class Orders::Productions::DetailsController < ApplicationController
  # GET /orders/productions/details
  # GET /orders/productions/details.json
  
  layout "default"

  def index
    @orders_productions_details = Orders::Productions::Detail.paginate(:page => params[:page])
    respond_to do |format|
      format.html
    end
  end

  # GET /orders/productions/details/1
  # GET /orders/productions/details/1.json
  def show
    @orders_productions_detail = Orders::Productions::Detail.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  # GET /orders/productions/details/new
  # GET /orders/productions/details/new.json
  def new
    @orders_productions_detail = Orders::Productions::Detail.new
    @orders_production = Orders::Production.find(params["header_id"])
    @orders_productions_details = @orders_production.details.paginate(:page => params[:page])
    respond_to do |format|
      format.js{ render 'update_list_form' }
    end
  end

  # GET /orders/productions/details/1/edit
  def edit
    @orders_productions_detail = Orders::Productions::Detail.find(params[:id])
    @orders_production = @orders_productions_detail.orders_production;
    @orders_productions_details = @orders_production.details.paginate(:page => params[:page])
    respond_to do |format|
      format.js
    end
  end

  # POST /orders/productions/details
  # POST /orders/productions/details.json
  def create
    @orders_productions_detail = Orders::Productions::Detail.new(params[:orders_productions_detail])
    @orders_productions_detail.orders_production = Orders::Production.find(params["header_id"])
    @orders_productions_details = @orders_productions_detail.orders_production.details.paginate(:page => params[:page])
    respond_to do |format|
      if @orders_productions_detail.save
        format.js{ 
          @orders_production = @orders_productions_detail.orders_production
          #@orders_productions_details = @production.details
          @orders_productions_detail = Orders::Productions::Detail.new
          render 'update_list_form' 
         }
      else
        format.html {
        redirect_to :back }
      end
    end
  end

  # PUT /orders/productions/details/1
  # PUT /orders/productions/details/1.json
  def update
    @orders_productions_detail = Orders::Productions::Detail.find(params[:id])
    @orders_production = @orders_productions_detail.orders_production;
    @orders_productions_details = @orders_production.details.paginate(:page => params[:page])
    respond_to do |format|
      if @orders_productions_detail.update_attributes(params[:orders_productions_detail])
        format.js{ 
          @orders_productions_detail = Orders::Productions::Detail.new
          render 'update_list_form' 
         }
      else
        format.html { 
        @notice = "Error al actualizar el registro"
        redirect_to :back }
      end
    end
  end

  def destroy
    @orders_productions_detail = Orders::Productions::Detail.find(params[:id])
    @orders_production = @orders_productions_detail.orders_production
    @orders_productions_details = @orders_production.details.paginate(:page => params[:page])
    @orders_productions_detail.destroy
    respond_to do |format|
        format.js{ 
          @orders_productions_detail =  Orders::Productions::Detail.new
          render 'update_list' 
         }
    end
  end
end

app/controllers/orders/productions_controller.rb
class Orders::ProductionsController < ApplicationController
  # GET /orders/productions
  # GET /orders/productions.json
  
  layout "dialog"

  def list
    @orders_productions = Orders::Production.paginate(:page => params[:page])
    delete_if_void @orders_productions
    @orders_productions = Orders::Production.paginate(:page => params[:page], :order => "created_at DESC")
  end

  def index
    list  
    @title = "Ordenes de producci&oacute;n"
    respond_to do |format|
      format.js
      format.pdf {
        @orders_productions = Orders::Production.paginate(:page => params[:page], :per_page => MAX_PER_PAGE)
          render :pdf => "file_name", 
          :template => '/orders/productions/index.html.haml',
          :header => { :html =>  { :template => 'pdf/header.pdf' } },
          :layout => 'pdf.html.erb' 
      }     
    end
  end

  # GET /orders/productions/1
  # GET /orders/productions/1.json
  def show
    @orders_production = Orders::Production.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  # GET /orders/productions/new
  # GET /orders/productions/new.json
  def new
    @orders_production = Orders::Production.new
    @orders_production.status = @default_status
    create 
#    respond_to do |format|
#      format.js # new.html.erb
#    end
  end

  # GET /orders/productions/1/edit
  def edit
    @orders_production = Orders::Production.find(params[:id])
  end

  # POST /orders/productions
  # POST /orders/productions.json
  def create
    #@orders_production = Orders::Production.new(params[:orders_production])
    @orders_production.user = current_user
    respond_to do |format|
      if @orders_production.save
        format.js { render action: 'show'  }
      else
        format.js { 
        render action: "new"}
      end
    end
  end

  def else_update
    respond_to do |format|
      if @orders_production.update_attributes(params[:orders_production])
        if @default_status == @orders_production.status
          format.js {  @notice = 'Registro guardado correctamente.' 
          render action: 'show'}
        else
          list
          format.js {  @notice = 'Registro guardado correctamente.' 
          render action: 'index'}
        end
      else
        format.js { 
        @notice = "Error al actualizar el registro"
        render action: "edit" }
      end
    end  
  end

  # PUT /orders/productions/1
  # PUT /orders/productions/1.json
  def update
    @orders_production = Orders::Production.find(params[:id])
    status_id = params[:orders_production][:status_id]
    if status_id == @close_status.id
      if ! @orders_production.close
        respond_to do |format|
          format.js { 
             @notice = "No se puede cambiar el estado a "+@close_status.name+", probablemente las cantidades sean incoherentes"
             render action: "edit"
          }
        end
      else else_update end
    else else_update end
  end

  # DELETE /orders/productions/1
  # DELETE /orders/productions/1.json
  def destroy
    @orders_production = Orders::Production.find(params[:id])
    @orders_production.destroy
    list
    respond_to do |format|
      format.js { render 'index' }
    end
  end
end

app/controllers/stock/production_controller.rb
class Stock::ProductionController < ApplicationController
  layout "stock_production"
  def index
  end

  def transactions
    @transactions = Transaction.where("from_stock = ? OR to_stock = ?", Stocks::Production.to_s, Stocks::Production.to_s).paginate(:page => params[:page])
    respond_to do |format|
      format.js
    end
  end

  def list_components
    @title = "Existencia de componentes en stock de producci&oacute;n"
    @components = Components::Item.paginate(:page => params[:page])
    respond_to do |format|
      format.js
      format.pdf {
        @components = Components::Item.paginate(:page => params[:page], :per_page => MAX_PER_PAGE)
          render :pdf => "file_name", 
          :template => '/stock/production/_list_components.html.haml',
          :header => { :html =>  { :template => 'pdf/header.pdf' } },
          :layout => 'special_pdf.html.erb'
      }     
    end
  end
  
  
  def list_products
    @title = "Existencia de productos en stock de producci&oacute;n"
    @products = Products::Composition.paginate(:page => params[:page])
    respond_to do |format|
      format.js
      format.pdf {
        @products = Products::Composition.paginate(:page => params[:page], :per_page => MAX_PER_PAGE)
          render :pdf => "file_name", 
          :template => '/stock/production/_list_products.html.haml',
          :header => { :html =>  { :template => 'pdf/header.pdf' } },
          :layout => 'special_pdf.html.erb'
      }     
    end
  end
end

app/helpers/orders/productions/details_helper.rb
module Orders::Productions::DetailsHelper
end

app/helpers/orders/productions_helper.rb
module Orders::ProductionsHelper
end

app/helpers/stock/production_helper.rb
module Stock::ProductionHelper
end

app/views/orders/productions/_form.html.haml
= form_for @orders_production, :html => { "data-remote"=>"true", style: "width:400px;" } do |f|
  - if @orders_production.errors.any?
    #error_explanation 
      %h2= "No se pudo guardar:"
      %ul
        - @orders_production.errors.full_messages.each do |msg|
          %li= msg
  
  .field
    = f.label :status_id, 'Estado'
    = f.collection_select(:status_id, Transactions::Status.all, :id, :name, { :disabled => lambda{|status| (@orders_production.status != @default_status && status == @reject_status) }, class: "required" })
  
  %div.ui-grid-a
    %div.ui-block-a
      %a.cancel{ data: {role:'button', icon: 'delete', theme: 'a' } } Cancelar
    %div.ui-block-b  
      %input{ close: "#componentPopup", type: 'submit', value: 'Guardar', data: { icon: 'plus', theme: 'b' } }

app/views/orders/productions/edit.html.haml
%h3{ data: {role:"header", theme:"d"} } Editar orden de producción
%div{ data: {role: "content", theme: "c" } }

  = render 'form'

app/views/orders/productions/edit.js.haml
:plain
  openPopup('#{escape_javascript render :file => "orders/productions/edit", :formats => [:html]}');
  showNotice('#{ @notice }');  

app/views/orders/productions/index.html.haml
= will_paginate @orders_productions
%ul{ data: { role: 'listview', inset: 'true', theme: 'c', filter: 'true' } }
  %li{ data: { role: 'list-divider' } }
  
    %div{ class: "ui-grid-d" }
  
      %div{ class: "ui-block-a" } N&uacute;mero
            
      %div{ class: "ui-block-b" } Estado
      
      %div{ class: "ui-block-c" } Usuario
      
      %div{ class: "ui-block-d" } Fecha
      
      %div{ class: "ui-block-e" } Opciones
  
  - @orders_productions.each do |orders_production|
    %li{ class: 'element detail'}
      %div{ class: "ui-grid-d" }
        
        %div{ class: "ui-block-a trim" }= orders_production.number
            
        %div{ class: "ui-block-b trim" }= orders_production.status.name
      
        %div{ class: "ui-block-c trim" }= orders_production.user.email
        
        %div{ class: "ui-block-d trim" }= orders_production.user.updated_at
  
        %div{ style:"width:262px;", class: "ui-block-e", data: { role: 'controlgroup', type: 'horizontal' } }
          - obj = orders_production
          - can_modify?(obj)
          - delete_css_class = !can?(:delete, obj) ? 'ui-disabled' : ''
          - edit_css_class = !can?(:edit, obj) ? 'ui-disabled' : ''
          %a{ href: orders_production_path(orders_production), data: { method: :delete, confirm: 'Esta seguro?', role: 'button', icon: 'delete', mini: 'true', remote: 'true' }, class: delete_css_class } Eliminar
          %a{ href: edit_orders_production_path(orders_production), data: { role: 'button', icon: 'grid', mini: 'true', remote: 'true'}, class: edit_css_class } Editar
          %a{ href: orders_production_path(orders_production), data: { role: 'button', icon: 'grid', mini: 'true', remote: 'true'} } Detalle
          
  - create_css_class = !can?(:create, Orders::Production.new) ? 'ui-disabled' : ''
  = link_to 'Agregar  ', new_orders_production_path, { style: 'width: 250px; float: right', data: { role: 'button', theme: 'b', icon: 'new', remote: 'true' }, class: create_css_class }
  
%br    
%div{ data: { role: 'controlgroup', type: 'horizontal' } }
  %a{ href: "#", data: { role: 'button', mini: 'true', pdf: 'true', href: orders_productions_url(:format => :pdf) } } Reporte

app/views/orders/productions/index.js.haml
:plain
  changeContent('#page #content',
    '#{escape_javascript render :file => "orders/productions/index", :formats => [:html]}'
  );
  showNotice('#{ @notice }');  

app/views/orders/productions/new.html.haml
%h3{ data: {role:"header", theme:"d"} }  Agregar orden de producción

%div{ data: {role: "content", theme: "a" } }

  = render 'form'

-#= link_to 'Atras', orders_productions_path

app/views/orders/productions/new.js.haml
:plain
  openPopup('#{escape_javascript render :file => "orders/productions/new", :formats => [:html]}');
  showNotice('#{ @notice }');  

app/views/orders/productions/show.html.haml
%ul{ data: { role: 'listview', theme: 'c' } }
  %li{ data: { role: 'list-divider'} }
    %div{ class: "ui-grid-c" }
        
      %div{ class: "ui-block-a" } Número
        
      %div{ class: "ui-block-b" } Estado
        
      %div{ class: "ui-block-c" } Usuario
      
      %div{ class: "ui-block-d" } Fecha
  %li
    %div{ class: "ui-grid-c" }
    
      %div{ class: "ui-block-a" }= @orders_production.number
    
      %div{ class: "ui-block-b" }= @orders_production.status.name
    
      %div{ class: "ui-block-c" }= @orders_production.user.email
      
      %div{ class: "ui-block-d" }= @orders_production.updated_at

  - @orders_productions_details = @orders_production.details.paginate(:page => params[:page])
  - @orders_productions_detail = Orders::Productions::Detail.new
%br
- obj = @orders_production
- if can_modify?(obj)
  %div#form
    = render 'orders/productions/details/form'

%div#list
  = render 'orders/productions/details/list'
  
= link_to 'Volver', orders_productions_path, { style: 'width: 250px; float: left', data: { role: 'button', theme: 'c', remote: 'true' } }
- create_css_class = can?(:create, Orders::Productions::Detail) ? '' : 'ui-disabled'
= link_to 'Agregar  ', new_orders_productions_detail_path(:header_id => @orders_production.id), { style: 'width: 250px; float: right', data: { role: 'button', theme: 'b', icon: 'new', remote: 'true' }, class: create_css_class  }

app/views/orders/productions/show.js.haml
:plain
  changeContent('#page #content',
    '#{escape_javascript render :file => "orders/productions/show", :formats => [:html]}'
  );
  showNotice('#{ @notice }');  