config/routes.rb
Stock::Application.routes.draw do
  namespace :requests do  namespace :transferences do  namespace :finished do  namespace :components do resources :details end end end end

  namespace :requests do  namespace :transferences do  namespace :finished do resources :components end end end

  get "entry/index", :to => "entry#index"

  get "activity", :to => 'activity#index'
  get 'activity/:id', :to => 'activity#show'

  get "stock/products/index", :to => "stock/products#index"
  get "stock/products/transactions", :to => "stock/products#transactions"
  get "stock/products/list_products"
  get "stock/products/list_components"
  
  get "stock/production/list_components"
  get "stock/production/list_products"
  get "stock/production/index", :to => "stock/production#index"
  get "stock/production/transactions", :to => "stock/production#transactions"

  get '/users', :to => 'users#index'

  namespace :stock do
    get "raw_material", :to => "raw_material#index"
    get "raw_material/list"
    get "raw_material/transactions", :to => "raw_material#transactions"
  end

  namespace :requests do  namespace :devolutions do  namespace :components do resources :details end end end

  namespace :orders do  namespace :productions do resources :details end end

  namespace :requests do  namespace :devolutions do  namespace :products do resources :details end end end

  namespace :requests do  namespace :transferences do  namespace :products do resources :details end end end

  namespace :requests do  namespace :transferences do  namespace :components do resources :details end end end

  namespace :requests do  namespace :purchases do  namespace :components do resources :details end end end

  namespace :products do  namespace :compositions do resources :details end end

  namespace :requests do  namespace :devolutions do resources :components end end

  namespace :orders do resources :productions end

  namespace :requests do  namespace :devolutions do resources :products end end

  namespace :requests do  namespace :transferences do resources :products end end

  namespace :requests do  namespace :transferences do resources :components end end

  namespace :requests do  namespace :purchases do resources :components end end

  namespace :products do resources :compositions end

  namespace :transactions do resources :statuses end

  namespace :locations do resources :cities end

  namespace :locations do resources :regions end

  namespace :locations do resources :countries end

  namespace :locations do resources :continents end

  namespace :components do resources :brands end

  namespace :components do  namespace :categories do resources :kinds end end

  namespace :settings do
    get '/', :to => 'settings#index'
    get 'permissions', :to => 'permissions#index'
    match 'permissions/:role_id', :to => 'permissions#of_role', :via => 'get'
    post 'permissions/save'
    resources :roles

    put 'configurations', :to => 'configurations#update'
    get 'company', :to => 'configurations#company'
  end

  namespace :components do
    resources :items
    resources :categories
  end

  devise_for :users, :path_names => {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }, :controllers => {
    registrations: 'users/registrations'
  }

  root :to => "stock/raw_material#index"

end

app/models/products.rb
module Products
  def self.table_name_prefix
    'products_'
  end
end

app/models/products/compositions.rb
module Products::Compositions
  def self.table_name_prefix
    'products_compositions_'
  end
end

app/controllers/products/compositions/details_controller.rb
class Products::Compositions::DetailsController < ApplicationController
  # GET /products/compositions/details
  # GET /products/compositions/details.json
  
  layout "default"

  def index
    @products_compositions_details = Products::Compositions::Detail.paginate(:page => params[:page])
    respond_to do |format|
      format.html
    end
  end

  # GET /products/compositions/details/1
  # GET /products/compositions/details/1.json
  def show
    @products_compositions_detail = Products::Compositions::Detail.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  # GET /products/compositions/details/new
  # GET /products/compositions/details/new.json
  def new
    @products_compositions_detail = Products::Compositions::Detail.new
    @products_composition = Products::Composition.find(params["header_id"])
    @products_compositions_details = @products_composition.details.paginate(:page => params[:page])
    respond_to do |format|
      format.js{ render 'update_list_form' }
    end
  end

  # GET /products/compositions/details/1/edit
  def edit
    @products_compositions_detail = Products::Compositions::Detail.find(params[:id])
    @products_composition = @products_compositions_detail.products_composition;
    @products_compositions_details = @products_composition.details.paginate(:page => params[:page])
    respond_to do |format|
      format.js
    end
  end

  # POST /products/compositions/details
  # POST /products/compositions/details.json
  def create
    @products_compositions_detail = Products::Compositions::Detail.new(params[:products_compositions_detail])
    @products_compositions_detail.products_composition = Products::Composition.find(params["header_id"])
    @products_compositions_details = @products_compositions_detail.products_composition.details.paginate(:page => params[:page])
    respond_to do |format|
      if @products_compositions_detail.save
        format.js{ 
          @products_composition = @products_compositions_detail.products_composition
          @products_compositions_detail = Products::Compositions::Detail.new
          render 'update_list_form' 
         }
      else
        format.html { @notice = 'Error al guardar el registro.'; redirect_to :back }
      end
    end
  end

  # PUT /products/compositions/details/1
  # PUT /products/compositions/details/1.json
  def update
    @products_compositions_detail = Products::Compositions::Detail.find(params[:id])
    @products_composition = @products_compositions_detail.products_composition;
    @products_compositions_details = @products_composition.details.paginate(:page => params[:page])
    respond_to do |format|
      if @products_compositions_detail.update_attributes(params[:products_compositions_detail])
        format.js{ 
          @products_compositions_detail = Products::Compositions::Detail.new
          render 'update_list_form' 
         }
      else
        format.html { 
        @notice = "Error al actualizar el registro"
        redirect_to :back }
      end
    end
  end

  def destroy
    @products_compositions_detail = Products::Compositions::Detail.find(params[:id])
    @products_composition = @products_compositions_detail.products_composition
    @products_compositions_details = @products_composition.details.paginate(:page => params[:page])
    @products_compositions_detail.destroy
    respond_to do |format|
        format.js{ 
          @products_compositions_detail =  Products::Compositions::Detail.new
          render 'update_list' 
         }
    end
  end
end

app/controllers/products/compositions_controller.rb
class Products::CompositionsController < ApplicationController
  # GET /products/compositions
  # GET /products/compositions.json
  
  layout "dialog"

  def list
    @products_compositions = Products::Composition.paginate(:page => params[:page])
  end

  def index
    list  
    @title = "Productos terminados"
    respond_to do |format|
      format.js
      format.pdf {
        @products_compositions = Products::Composition.paginate(:page => params[:page], :per_page => MAX_PER_PAGE)
          render :pdf => "file_name", 
          :template => '/products/compositions/index.html.haml',
          :header => { :html =>  { :template => 'pdf/header.pdf' } },
          :layout => 'pdf.html.erb' 
      }     
    end
  end

  # GET /products/compositions/1
  # GET /products/compositions/1.json
  def show
    @products_composition = Products::Composition.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  # GET /products/compositions/new
  # GET /products/compositions/new.json
  def new
    @products_composition = Products::Composition.new
    respond_to do |format|
      format.js # new.html.erb
    end
  end

  # GET /products/compositions/1/edit
  def edit
    @products_composition = Products::Composition.find(params[:id])
  end

  # POST /products/compositions
  # POST /products/compositions.json
  def create
    @products_composition = Products::Composition.new(params[:products_composition])
    respond_to do |format|
      if @products_composition.save
        format.js { @notice = 'Registro actualizado correctamente.' 
        render action: 'show'}
      else
        format.js { @notice = 'Error al guardar el registro.' 
        render action: "new"}
      end
    end
  end

  # PUT /products/compositions/1
  # PUT /products/compositions/1.json
  def update
    @products_composition = Products::Composition.find(params[:id])

    respond_to do |format|
      if @products_composition.update_attributes(params[:products_composition])
        format.js { render action: 'show'; @notice = 'Registro guardado correctamente.' }
      else
        format.js { 
        @notice = "Error al actualizar el registro"
        render action: "edit" }
      end
    end
  end

  # DELETE /products/compositions/1
  # DELETE /products/compositions/1.json
  def destroy
    @products_composition = Products::Composition.find(params[:id])
    @products_composition.destroy
    list
    respond_to do |format|
      format.js { render 'index' }
    end
  end
end

app/controllers/requests/devolutions/components/details_controller.rb
class Requests::Devolutions::Components::DetailsController < ApplicationController
  # GET /requests/devolutions/components/details
  # GET /requests/devolutions/components/details.json
  
  layout "default"

  def index
    @requests_devolutions_components_details = Requests::Devolutions::Components::Detail.paginate(:page => params[:page])
    respond_to do |format|
      format.html
    end
  end

  # GET /requests/devolutions/components/details/1
  # GET /requests/devolutions/components/details/1.json
  def show
    @requests_devolutions_components_detail = Requests::Devolutions::Components::Detail.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  # GET /requests/devolutions/components/details/new
  # GET /requests/devolutions/components/details/new.json
  def new
    @requests_devolutions_components_detail = Requests::Devolutions::Components::Detail.new
    @requests_devolutions_component = Requests::Devolutions::Component.find(params["header_id"])
    @requests_devolutions_components_details = @requests_devolutions_component.details.paginate(:page => params[:page])
    respond_to do |format|
      format.js{ render 'update_list_form' }
    end
  end

  # GET /requests/devolutions/components/details/1/edit
  def edit
    @requests_devolutions_components_detail = Requests::Devolutions::Components::Detail.find(params[:id])
    @requests_devolutions_component = @requests_devolutions_components_detail.requests_devolutions_component;
    @requests_devolutions_components_details = @requests_devolutions_component.details.paginate(:page => params[:page])
    respond_to do |format|
      format.js
    end
  end

  # POST /requests/devolutions/components/details
  # POST /requests/devolutions/components/details.json
  def create
    @requests_devolutions_components_detail = Requests::Devolutions::Components::Detail.new(params[:requests_devolutions_components_detail])
    @requests_devolutions_components_detail.requests_devolutions_component = Requests::Devolutions::Component.find(params["header_id"])
    @requests_devolutions_components_details = @requests_devolutions_components_detail.requests_devolutions_component.details.paginate(:page => params[:page])
    respond_to do |format|
      if @requests_devolutions_components_detail.save
        format.js{ 
          @requests_devolutions_component = @requests_devolutions_components_detail.requests_devolutions_component
          @requests_devolutions_components_detail = Requests::Devolutions::Components::Detail.new
          render 'update_list_form' 
         }
      else
        format.html { @notice = 'Error al guardar el registro.'; redirect_to :back }
      end
    end
  end

  # PUT /requests/devolutions/components/details/1
  # PUT /requests/devolutions/components/details/1.json
  def update
    @requests_devolutions_components_detail = Requests::Devolutions::Components::Detail.find(params[:id])
    @requests_devolutions_component = @requests_devolutions_components_detail.requests_devolutions_component;
    @requests_devolutions_components_details = @requests_devolutions_component.details.paginate(:page => params[:page])
    respond_to do |format|
      if @requests_devolutions_components_detail.update_attributes(params[:requests_devolutions_components_detail])
        format.js{ 
          @requests_devolutions_components_detail = Requests::Devolutions::Components::Detail.new
          render 'update_list_form' 
         }
      else
        format.html { 
        @notice = "Error al actualizar el registro"
        redirect_to :back }
      end
    end
  end

  def destroy
    @requests_devolutions_components_detail = Requests::Devolutions::Components::Detail.find(params[:id])
    @requests_devolutions_component = @requests_devolutions_components_detail.requests_devolutions_component
    @requests_devolutions_components_details = @requests_devolutions_component.details.paginate(:page => params[:page])
    @requests_devolutions_components_detail.destroy
    respond_to do |format|
        format.js{ 
          @requests_devolutions_components_detail =  Requests::Devolutions::Components::Detail.new
          render 'update_list' 
         }
    end
  end
end

app/controllers/requests/devolutions/components_controller.rb
class Requests::Devolutions::ComponentsController < ApplicationController
  # GET /requests/devolutions/components
  # GET /requests/devolutions/components.json
  
  layout "dialog"

  def list
    @requests_devolutions_components = Requests::Devolutions::Component.paginate(:page => params[:page])
    delete_if_void @requests_devolutions_components
    @requests_devolutions_components = Requests::Devolutions::Component.paginate(:page => params[:page], :order => "created_at DESC")
  end

  def index
    list  
    @title = "Pedidos de devoluci&oacute;n de componentes"
    respond_to do |format|
      format.js
      format.pdf {
        @requests_devolutions_components = Requests::Devolutions::Component.paginate(:page => params[:page], :per_page => MAX_PER_PAGE)
          render :pdf => "file_name", 
          :template => '/requests/devolutions/components/index.html.haml',
          :header => { :html =>  { :template => 'pdf/header.pdf' } },
          :layout => 'pdf.html.erb' 
      }     
    end
  end

  # GET /requests/devolutions/components/1
  # GET /requests/devolutions/components/1.json
  def show
    @requests_devolutions_component = Requests::Devolutions::Component.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  # GET /requests/devolutions/components/new
  # GET /requests/devolutions/components/new.json
  def new
    @requests_devolutions_component = Requests::Devolutions::Component.new
    @hide_status_select = true
    respond_to do |format|
      format.js # new.html.erb
    end
  end

  # GET /requests/devolutions/components/1/edit
  def edit
    @requests_devolutions_component = Requests::Devolutions::Component.find(params[:id])
  end

  # POST /requests/devolutions/components
  # POST /requests/devolutions/components.json
  def create
    @requests_devolutions_component = Requests::Devolutions::Component.new(params[:requests_devolutions_component])
    @requests_devolutions_component.status = @default_status
    @requests_devolutions_component.user = current_user
    respond_to do |format|
      if @requests_devolutions_component.save
        format.js { render action: 'show' }
      else
        format.js { @notice =  'Error al guardar el registro.'
        render action: "new" }
      end
    end
  end

  def else_update
    respond_to do |format|
      if @requests_devolutions_component.update_attributes(params[:requests_devolutions_component])
        if @default_status == @requests_devolutions_component.status
          format.js {  @notice =  'Registro guardado correctamente.' 
          render action: 'show'}
        else
          list
          format.js {  @notice =  'Registro guardado correctamente.' 
          render action: 'index'}
        end
      else
        format.js { 
        @notice = "Error al actualizar el registro"
        render action: "edit" }
      end
    end
  end

  # PUT /requests/devolutions/components/1
  # PUT /requests/devolutions/components/1.json
  def update
    @requests_devolutions_component = Requests::Devolutions::Component.find(params[:id])
    status_id = params[:requests_devolutions_component][:status_id]
    if status_id == @close_status.id
      if ! @requests_devolutions_component.close
        respond_to do |format|
          format.js { 
             @notice = "No se puede cambiar el estado a "+@close_status.name+", probablemente las cantidades sean incoherentes"
             render action: "edit"
          }
        end
      else else_update end
    else else_update end
  end

  # DELETE /requests/devolutions/components/1
  # DELETE /requests/devolutions/components/1.json
  def destroy
    @requests_devolutions_component = Requests::Devolutions::Component.find(params[:id])
    @requests_devolutions_component.destroy
    list
    respond_to do |format|
      format.js { render 'index' }
    end
  end

end

app/views/requests/devolutions/products/_form.html.haml
= form_for @requests_devolutions_product, :html => { "data-remote"=>"true", style: "width:400px;" } do |f|
  - if @requests_devolutions_product.errors.any?
    #error_explanation 
      %h2= "No se pudo guardar:"
      %ul
        - @requests_devolutions_product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :reason, 'Motivo' 
    = f.text_field :reason, { class: "required ", "maxlength" => "60", "minlength" => "2"  }

  - if !@hide_status_select
    .field
      = f.label :status_id, 'Estado'
      = f.collection_select(:status_id, Transactions::Status.all, :id, :name, { :disabled => lambda{|status| (@requests_devolutions_product.status != @default_status && status == @reject_status) }, class: "required" })
      
  %div.ui-grid-a
    %div.ui-block-a
      %a.cancel{ data: {role:'button', icon: 'delete', theme: 'a' } } Cancelar
    %div.ui-block-b  
      %input{ close: "#componentPopup", type: 'submit', value: 'Guardar', data: { icon: 'plus', theme: 'b' } }

app/views/requests/devolutions/products/edit.html.haml
%h3{ data: {role:"header", theme:"d"} } Editar devolución
%div{ data: {role: "content", theme: "c" } }

  = render 'form'

app/views/requests/devolutions/products/edit.js.haml
:plain
  openPopup('#{escape_javascript render :file => "requests/devolutions/products/edit", :formats => [:html]}');
  showNotice('#{ @notice }');  

app/views/requests/devolutions/products/index.html.haml
= will_paginate @requests_devolutions_products
%ul{ data: { role: 'listview', inset: 'true', theme: 'c', filter: 'true' } }
  %li{ data: { role: 'list-divider' } }
  
    %div{ class: "ui-grid-e" }
  
      %div{ class: "ui-block-a" } N&uacute;mero
            
      %div{ class: "ui-block-b" } Motivo
      
      %div{ class: "ui-block-c" } Usuario
      
      %div{ class: "ui-block-d" } Estado
      
      %div{ class: "ui-block-e" } Fecha
      
      %div{ class: "ui-block-f" } Opciones      
  
  - @requests_devolutions_products.each do |requests_devolutions_product|
    %li{ class: 'element detail'}
      %div{ class: "ui-grid-e" }
      
        %div{ class: "ui-block-a trim" }= requests_devolutions_product.number
            
        %div{ class: "ui-block-b trim" }= requests_devolutions_product.reason
      
        %div{ class: "ui-block-c trim" }= requests_devolutions_product.user.email
      
        %div{ class: "ui-block-d trim" }= requests_devolutions_product.status.name
      
        %div{ class: "ui-block-e trim" }= requests_devolutions_product.updated_at
  
        %div{ style:"width:262px;", class: "ui-block-f", data: { role: 'controlgroup', type: 'horizontal' } }
          - obj = requests_devolutions_product
          - can_modify?(obj)
          - delete_css_class = !can?(:delete, obj) ? 'ui-disabled' : ''
          - edit_css_class = !can?(:edit, obj) ? 'ui-disabled' : ''
          %a{ href: requests_devolutions_product_path(requests_devolutions_product), data: { method: :delete, confirm: 'Esta seguro?', role: 'button', icon: 'delete', mini: 'true', remote: 'true' }, class: delete_css_class } Eliminar
          %a{ href: edit_requests_devolutions_product_path(requests_devolutions_product), data: { role: 'button', icon: 'grid', mini: 'true', remote: 'true'}, class: edit_css_class } Editar
          %a{ href: requests_devolutions_product_path(requests_devolutions_product), data: { role: 'button', icon: 'grid', mini: 'true', remote: 'true'} } Detalle
          
  - create_css_class = !can?(:create, Requests::Devolutions::Product.new) ? 'ui-disabled' : ''
  = link_to 'Agregar  ', new_requests_devolutions_product_path, { style: 'width: 250px; float: right', data: { role: 'button', theme: 'b', icon: 'new', remote: 'true' }, class: create_css_class }
  

%br    
%div{ data: { role: 'controlgroup', type: 'horizontal' } }
  %a{ href: "#", data: { role: 'button', mini: 'true', pdf: 'true', href: requests_devolutions_products_url(:format => :pdf) } } Reporte

app/views/requests/devolutions/products/index.js.haml
:plain
  changeContent('#page #content',
    '#{escape_javascript render :file => "requests/devolutions/products/index", :formats => [:html]}'
  );
  showNotice('#{ @notice }');  

app/views/requests/devolutions/products/new.html.haml
%h3{ data: {role:"header", theme:"d"} }  Agregar devolución

%div{ data: {role: "content", theme: "a" } }

  = render 'form'

-#= link_to 'Atras', requests_devolutions_products_path

app/views/requests/devolutions/products/new.js.haml
:plain
  openPopup('#{escape_javascript render :file => "requests/devolutions/products/new", :formats => [:html]}');
  showNotice('#{ @notice }');  

app/views/requests/devolutions/products/show.html.haml
%ul{ data: { role: 'listview', theme: 'c' } }
  %li{ data: { role: 'list-divider'} }
    %div{ class: "ui-grid-d" }
        
      %div{ class: "ui-block-a" } Número
        
      %div{ class: "ui-block-b" } Estado
        
      %div{ class: "ui-block-c" } Motivo
        
      %div{ class: "ui-block-d" } Fecha
      
      %div{ class: "ui-block-e" } Usuario      
      
  %li  
    %div{ class: "ui-grid-d" }
    
      %div{ class: "ui-block-a trim" }= @requests_devolutions_product.number
    
      %div{ class: "ui-block-b trim" }= @requests_devolutions_product.status.name
      
      %div{ class: "ui-block-c trim" }= @requests_devolutions_product.reason

      %div{ class: "ui-block-d trim" }= @requests_devolutions_product.updated_at
      
      %div{ class: "ui-block-e trim" }= @requests_devolutions_product.user.email    

  - @requests_devolutions_products_details = @requests_devolutions_product.details.paginate(:page => params[:page])
  - @requests_devolutions_products_detail = Requests::Devolutions::Products::Detail.new

%br
- obj = @requests_devolutions_product
- if can_modify?(obj)
  %div#form
    = render 'requests/devolutions/products/details/form'

%div#list
  = render 'requests/devolutions/products/details/list'
  
= link_to 'Volver', requests_devolutions_products_path, { style: 'width: 250px; float: left', data: { role: 'button', theme: 'c', remote: 'true' } }
- create_css_class = can?(:create, Requests::Devolutions::Products::Detail) ? '' : 'ui-disabled'
= link_to 'Agregar  ', new_requests_devolutions_products_detail_path(:header_id => @requests_devolutions_product.id), { style: 'width: 250px; float: right', data: { role: 'button', theme: 'b', icon: 'new', remote: 'true' }, class: create_css_class }

app/views/requests/devolutions/products/show.js.haml
:plain
  changeContent('#page #content',
    '#{escape_javascript render :file => "requests/devolutions/products/show", :formats => [:html]}'
  );
  showNotice('#{ @notice }');  